apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextgen-ce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ccm/api
    {{- if .Values.serviceUpstream}}
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: {{.Values.name}}.{{.Values.namespace.name}}.svc.cluster.local
  {{- end}}
  spec:
    ingressClassName: {{.Values.ingressClass}}
    rules:
    - http:
      paths:
      - path: {{.Values.pathPrefix}}/ccm/api
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{.Values.name}}
            port:
              number: 6340
