apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextgen-ce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ccm/api
  spec:
    ingressClassName: {{.Values.ingress.className}}
    rules:
    - http:
      paths:
      - path: ccm/api
        pathType: ImplementationSpecific
        backend:
          service:
            name: nextgen-ce
            port:
              number: {{ .Values.service.port }}
