apiVersion: v1
kind: Secret
metadata:
  name: nextgen-ce
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextgen-ce.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "nextgen-ce.generateSecrets" . }}